apiVersion: "serving.kserve.io/v1alpha2"
kind: "InferenceService"
metadata:
  name: "iris"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
    predictor:
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
