apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-pipeline-v1-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.4, pipelines.kubeflow.org/pipeline_compilation_time: '2021-10-07T18:42:16.786867',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "hello-world-pipeline-v1"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.4}
spec:
  entrypoint: hello-world-pipeline-v1
  templates:
  - name: echo
    container:
      args: [echo "hello world"]
      command: [sh, -c]
      image: library/bash:4.4.23
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.4
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: hello-world-pipeline-v1
    dag:
      tasks:
      - {name: echo, template: echo}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
