apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: iris-experiment-vml
  namespace: ''
spec:
  maxTrialCount: 12
  parallelTrialCount: 3
  maxFailedTrialCount: 3
  resumePolicy: LongRunning
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
    additionalMetricNames: []
    metricStrategies:
      - name: accuracy
        value: max
  algorithm:
    algorithmName: random
    algorithmSettings: []
  parameters:
    - name: n_neighbors
      parameterType: int
      feasibleSpace:
        min: '1'
        max: '10'
  metricsCollectorSpec:
    collector:
      kind: StdOut
  trialTemplate:
    primaryContainerName: training-container
    successCondition: status.conditions.#(type=="Complete")#|#(status=="True")#
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    retain: false
    trialParameters:
      - name: n_neighbors
        reference: n_neighbors
        description: Number of the neighbors
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: 'false'
          spec:
            containers:
              - command:
                  - python3
                  - iris_classification.py
                  - build_model
                  - knn
                  - ${trialParameters.n_neighbors}
                image: docker.io/annajung/iris
                name: training-container
            restartPolicy: Never
